export const mockProducts = [
    {
        "id": "1",
        "owner_id": "1",
        "owner": "anonimus",
        "category_id": "1",
        "category": "Для отдыха",
        "name": 'Электрогриль',
        "description": 'Краткое описание товара',
        "image": 'https://www.k-marumie.com/wpsys/wp-content/uploads/2025/01/0001.jpg',
        "price": 500,
        "deposit": 0,
        "city": "Екатеринбург",
        "created_at": "2026-01-15T14:30:00.000Z",
    },
    {
        "id": "2",
        "owner_id": "2",
        "owner": "anonimus",
        "category_id": "2",
        "category": "Хобби",
        "name": 'Коллекция книг',
        "description": 'Краткое описание товара',
        "image": 'https://www.k-marumie.com/wpsys/wp-content/uploads/2025/01/0001.jpg',
        "price": 100,
        "deposit": 0,
        "city": "Москва",
        "created_at": "2026-02-15T14:30:00.000Z",
    },
    {
        "id": "3",
        "owner_id": "3",
        "owner": "anonimus",
        "category_id": "3",
        "category": "Рыбалка",
        "name": 'Лодочный мотор',
        "description": 'Лодочный мотор — это двигатель, устанавливаемый на лодку или другое маломерное плавательное средство и предназначенный для его приведения в движение. Основные задачи — обеспечение тяги, манёвренности и управления движением по водной поверхности. Некоторые компоненты лодочного мотора:двигатель внутреннего сгорания(ДВС);топливная система обеспечивает подачу топлива в двигатель, смешивая его с воздухом для образования горючей смеси;система зажигания создаёт искру, необходимую для воспламенения топливной смеси в цилиндрах двигателя;',
        "image": 'https://www.k-marumie.com/wpsys/wp-content/uploads/2025/01/0001.jpg',
        "price": 450,
        "deposit": 0,
        "city": "Москва",
        "created_at": "2026-01-15T14:30:00.000Z",
    },
    {
        "id": "4",
        "owner_id": "4",
        "owner": "anonimus",
        "category_id": "4",
        "category": "Для отдыха",
        "name": 'Палатка',
        "description": 'Краткое описание товара',
        "image": 'https://www.k-marumie.com/wpsys/wp-content/uploads/2025/01/0001.jpg',
        "price": 1000,
        "deposit": 0,
        "city": "Москва",
        "created_at": "2025-11-10T14:30:00.000Z",
    },
    {
        "id": "5",
        "owner_id": "5",
        "owner": "anonimus",
        "category_id": "5",
        "category": "Авто",
        "name": 'Reno Logan',
        "description": 'Краткое описание товара',
        "image": 'https://www.k-marumie.com/wpsys/wp-content/uploads/2025/01/0001.jpg',
        "price": 3000,
        "deposit": 0,
        "city": "Томск",
        "created_at": "2026-02-10T14:30:00.000Z",
    },
    {
        "id": "6",
        "owner_id": "6",
        "owner": "anonimus",
        "category_id": "6",
        "category": "Дом и ремонт",
        "name": 'Набор инструментов',
        "description": 'Краткое описание товара',
        "image": 'https://www.k-marumie.com/wpsys/wp-content/uploads/2025/01/0001.jpg',
        "price": 300,
        "deposit": 0,
        "city": "Москва",
        "created_at": "2025-12-10T14:30:00.000Z",
    }
]

export const categories = [
    { value: "", label: "Все" },
    { value: "Рыбалка", label: "Рыбалка" },
    { value: "Авто", label: "Авто" },
    { value: "Для отдыха", label: "Для отдыха" },
    { value: "Дом и ремонт", label: "Дом и ремонт" },
    { value: "Хобби", label: "Хобби" }
]

export const cities = [
    { value: "", label: "Все" },
    { value: "Москва", label: "Москва" },
    { value: "Екатеринбург", label: "Екатеринбург" },
    { value: "Санкт-Петербург", label: "Санкт-Петербург" },
    { value: "Новосибирск", label: "Новосибирск" },
    { value: "Томск", label: "Томск" }
]